name: Share to Mastodon
on:
  push:
    branches: [ main ]

jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - name: Share to Mastodon
        uses: cbrgm/mastodon-github-action@v1
        with:
          access-token: ${{ qocxDPR09zu-1VjEI4hTJ14c6M7_nMrgoRZtMOeDDx4 }}  
          message: "새로운 업데이트가 있습니다! 🚀"
          visibility: "public"
          url: "https://el.elbarand.pics/" 
