name: "Mastodon Share Workflow"
on:
  push:
    branches:
      - whipping-edition
  release:
    types:
      - published

jobs:
  share:
    name: "Share to Mastodon"
    runs-on: ubuntu-latest
    steps:
      - name: "Post to Mastodon"
        uses: cbrgm/mastodon-github-action@v1
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          message: "New update in my GitHub repository! 🚀 Check it out: ${{ github.event.repository.html_url }}"
          visibility: public
          url: "https://el.elbarand.pics/"
